/**
 * Tipos de tarea soportados por la cola interna.
 */
const TASK_TYPES = {
  ACCOUNT_VERIFICATION: "ACCOUNT_VERIFICATION",
  RESEND_VERIFICATION_CODE: "RESEND_VERIFICATION_CODE",
  PASSWORD_RECOVERY: "PASSWORD_RECOVERY",
  CUSTOM_NOTIFICATION: "CUSTOM_NOTIFICATION",
  ATTACHMENT_NOTIFICATION: "ATTACHMENT_NOTIFICATION"
};

/**
 * Estados posibles de cada tarea en la cola.
 */
const TASK_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  SENT: "SENT",
  FAILED: "FAILED"
};

module.exports = { TASK_TYPES, TASK_STATUS };
